<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="<?php echo $this->basePath(). '/css/bootstrap.css'?>">

    <!-- Optional theme -->
    <link rel="stylesheet" href="<?php echo $this->basePath(). '/css/bootstrap-theme.min.css'?>">

    <!-- Latest compiled and minified JavaScript -->
    <script src="<?php echo $this->basePath(). '/js/boostrap.min.js'?>"></script>

    <!-- custom CSS -->
    <link rel="stylesheet" href="<?php echo $this->basePath(). '/css/style.css'?>">
</head>
<body class="container-fluid main-container">
<div id="page" class="container">
<header class="row blog-header header" role="banner">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="static-header">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="site-branding">
                    <h1 class="blog-title"><a href="<?php echo $this->url('home') ?>" rel="home">
                            <img src="<?php echo ($this->basePath(). '/img/Logo.PNG') ;?>" alt="Course Book Store Logo"
                                 width = "300" height = "100"/>
                        </a></h1>
                </div><!-- .site-branding -->

            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="../university/">University</a></li>
                    <li class="active"><a href="./">Static top <span class="sr-only">(current)</span></a></li>
                    <li><a href="../navbar-fixed-top/">Fixed top</a></li>
                </ul>
            </div><!--/.nav-collapse -->
            <div class="col-md-12">
                <form class="col-md-8" role="search">
                    <input type="text" class="col-md-10 search-input" placeholder="Search">
                    <button type="submit" class="glyphicon glyphicon-search col-md-2"></button>
                </form>
            </div>
        </div>
    </nav>
</header>
<!-- #masthead -->


<div class="container main-content">
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies
            Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
</div>
<!-- /container -->
<?php echo $this->inlineScript() ?>
    </div>
</body>
</html>
